

-- NOTE :
-- Ce fichier configure uniquement le schéma PostgreSQL, les tables,
-- les fonctions RPC et les droits Supabase.
-- L'envoi des e-mails n'est pas géré ici : il est fait par l'Edge Function
-- supabase/functions/send-email/index.ts, avec les secrets SMTP Supabase.
-- ==========================================================
-- Réservations AMMA — schéma Supabase
-- ==========================================================
-- À exécuter dans Supabase > SQL Editor.
--
-- Le navigateur peut :
--   - lire uniquement les créneaux (date, heure, Libre/Réservé)
--   - appeler les fonctions sécurisées de demande, confirmation et annulation
--
-- Le navigateur NE PEUT PAS lire la table contenant les noms et e-mails.
-- ==========================================================

create extension if not exists pgcrypto;

create table if not exists public.amma_slots (
  id bigint generated by default as identity primary key,
  session_date date not null,
  start_time time not null,
  end_time time not null,
  visible boolean not null default true,
  booked boolean not null default false,
  created_at timestamptz not null default now(),

  constraint amma_slots_unique_slot unique (session_date, start_time),
  constraint amma_slots_valid_time check (end_time > start_time)
);

alter table public.amma_slots
  add column if not exists visible boolean not null default true;

create table if not exists public.amma_bookings (
  id bigint generated by default as identity primary key,
  slot_id bigint not null unique references public.amma_slots(id) on delete cascade,
  firstname text not null,
  lastname text not null,
  email text not null,
  cancellation_token uuid not null unique default gen_random_uuid(),
  confirmation_email_sent_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.amma_bookings
  add column if not exists confirmation_email_sent_at timestamptz;

create table if not exists public.amma_cancellations (
  id bigint generated by default as identity primary key,
  slot_id bigint references public.amma_slots(id) on delete set null,
  firstname text not null,
  lastname text not null,
  email text not null,
  session_date date not null,
  start_time time not null,
  end_time time not null,
  email_token uuid not null unique default gen_random_uuid(),
  cancellation_email_sent_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.amma_booking_requests (
  id bigint generated by default as identity primary key,
  slot_id bigint not null references public.amma_slots(id) on delete cascade,
  firstname text not null,
  lastname text not null,
  email text not null,
  confirmation_token uuid not null unique default gen_random_uuid(),
  confirmation_email_sent_at timestamptz,
  confirmed_at timestamptz,
  expires_at timestamptz not null default now() + interval '2 hours',
  created_at timestamptz not null default now()
);

create table if not exists public.amma_admins (
  email text primary key,
  created_at timestamptz not null default now(),

  constraint amma_admins_email_lowercase check (email = lower(email))
);

alter table public.amma_slots enable row level security;
alter table public.amma_bookings enable row level security;
alter table public.amma_cancellations enable row level security;
alter table public.amma_booking_requests enable row level security;
alter table public.amma_admins enable row level security;

-- Le public et les admins connectés ne voient que l'état des créneaux.
drop policy if exists "Public can read AMMA slots" on public.amma_slots;
create policy "Public can read AMMA slots"
on public.amma_slots
for select
to anon, authenticated
using (visible = true);

-- AUCUNE policy SELECT/INSERT/UPDATE/DELETE sur amma_bookings,
-- amma_booking_requests ni amma_cancellations. Les tables contenant les
-- noms/e-mails restent donc inaccessibles directement depuis le navigateur.

-- AUCUNE policy SELECT/INSERT/UPDATE/DELETE sur amma_admins.
-- Les autorisations admin passent par des fonctions security definer.

create or replace function public.book_amma_slot(
  p_slot_id bigint,
  p_firstname text,
  p_lastname text,
  p_email text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_token uuid;
  v_updated integer;
begin
  if nullif(trim(p_firstname), '') is null
     or nullif(trim(p_lastname), '') is null
     or nullif(trim(p_email), '') is null then
    raise exception 'missing_fields';
  end if;

  if lower(trim(p_email)) !~ '^[^@\s]+@inria\.fr$' then
    raise exception 'invalid_email_domain';
  end if;

  update public.amma_slots
     set booked = true
   where id = p_slot_id
     and booked = false
     and visible = true;

  get diagnostics v_updated = row_count;

  if v_updated <> 1 then
    raise exception 'slot_already_booked';
  end if;

  v_token := gen_random_uuid();

  insert into public.amma_bookings (
    slot_id,
    firstname,
    lastname,
    email,
    cancellation_token
  )
  values (
    p_slot_id,
    trim(p_firstname),
    trim(p_lastname),
    lower(trim(p_email)),
    v_token
  );

  return v_token;
end;
$$;

create or replace function public.create_amma_booking_request(
  p_slot_id bigint,
  p_firstname text,
  p_lastname text,
  p_email text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_token uuid;
begin
  if nullif(trim(p_firstname), '') is null
     or nullif(trim(p_lastname), '') is null
     or nullif(trim(p_email), '') is null then
    raise exception 'missing_fields';
  end if;

  if lower(trim(p_email)) !~ '^[^@\s]+@inria\.fr$' then
    raise exception 'invalid_email_domain';
  end if;

  if not exists (
    select 1
     from public.amma_slots
     where id = p_slot_id
       and booked = false
       and visible = true
  ) then
    raise exception 'slot_already_booked';
  end if;

  v_token := gen_random_uuid();

  insert into public.amma_booking_requests (
    slot_id,
    firstname,
    lastname,
    email,
    confirmation_token
  )
  values (
    p_slot_id,
    trim(p_firstname),
    trim(p_lastname),
    lower(trim(p_email)),
    v_token
  );

  return v_token;
end;
$$;

create or replace function public.confirm_amma_booking_request(
  p_token uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.amma_booking_requests%rowtype;
  v_slot public.amma_slots%rowtype;
  v_cancellation_token uuid;
  v_updated integer;
begin
  select *
    into v_request
    from public.amma_booking_requests
   where confirmation_token = p_token
   for update;

  if v_request.id is null then
    raise exception 'request_not_found';
  end if;

  if v_request.confirmed_at is not null then
    raise exception 'request_already_confirmed';
  end if;

  if v_request.expires_at < now() then
    raise exception 'request_expired';
  end if;

  update public.amma_slots
     set booked = true
   where id = v_request.slot_id
     and booked = false
     and visible = true
   returning * into v_slot;

  get diagnostics v_updated = row_count;

  if v_updated <> 1 then
    raise exception 'slot_already_booked';
  end if;

  v_cancellation_token := gen_random_uuid();

  insert into public.amma_bookings (
    slot_id,
    firstname,
    lastname,
    email,
    cancellation_token
  )
  values (
    v_request.slot_id,
    v_request.firstname,
    v_request.lastname,
    v_request.email,
    v_cancellation_token
  );

  update public.amma_booking_requests
     set confirmed_at = now()
   where id = v_request.id;

  return jsonb_build_object(
    'cancellation_token', v_cancellation_token,
    'session_date', v_slot.session_date,
    'start_time', v_slot.start_time,
    'end_time', v_slot.end_time
  );
end;
$$;

drop function if exists public.cancel_amma_booking(uuid);

create or replace function public.cancel_amma_booking(
  p_token uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_booking record;
  v_email_token uuid;
begin
  select
    b.id,
    b.slot_id,
    b.firstname,
    b.lastname,
    b.email,
    s.session_date,
    s.start_time,
    s.end_time
    into v_booking
    from public.amma_bookings b
    join public.amma_slots s
      on s.id = b.slot_id
   where b.cancellation_token = p_token
   for update of b;

  if v_booking.id is null then
    return jsonb_build_object('cancelled', false);
  end if;

  delete from public.amma_bookings
   where id = v_booking.id;

  update public.amma_slots
     set booked = false
   where id = v_booking.slot_id;

  insert into public.amma_cancellations (
    slot_id,
    firstname,
    lastname,
    email,
    session_date,
    start_time,
    end_time
  )
  values (
    v_booking.slot_id,
    v_booking.firstname,
    v_booking.lastname,
    v_booking.email,
    v_booking.session_date,
    v_booking.start_time,
    v_booking.end_time
  )
  returning email_token into v_email_token;

  return jsonb_build_object(
    'cancelled', true,
    'cancellation_email_token', v_email_token
  );
end;
$$;

create or replace function public.is_amma_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
      from public.amma_admins
     where email = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

drop function if exists public.admin_list_amma_reservations();

create or replace function public.admin_list_amma_reservations()
returns table (
  slot_id bigint,
  session_date date,
  start_time time,
  end_time time,
  visible boolean,
  booked boolean,
  booking_id bigint,
  firstname text,
  lastname text,
  email text,
  booked_at timestamptz,
  confirmation_email_sent_at timestamptz,
  pending_requests bigint
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_amma_admin() then
    raise exception 'admin_access_required';
  end if;

  return query
  select
    s.id as slot_id,
    s.session_date,
    s.start_time,
    s.end_time,
    s.visible,
    s.booked,
    b.id as booking_id,
    b.firstname,
    b.lastname,
    b.email,
    b.created_at as booked_at,
    b.confirmation_email_sent_at,
    coalesce(r.pending_requests, 0) as pending_requests
  from public.amma_slots s
  left join public.amma_bookings b
    on b.slot_id = s.id
  left join lateral (
    select count(*) as pending_requests
      from public.amma_booking_requests br
     where br.slot_id = s.id
       and br.confirmed_at is null
       and br.expires_at >= now()
  ) r on true
  order by s.session_date, s.start_time;
end;
$$;

create or replace function public.admin_list_amma_sessions()
returns table (
  session_date date,
  visible boolean,
  slots_count bigint,
  booked_count bigint,
  pending_requests bigint
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_amma_admin() then
    raise exception 'admin_access_required';
  end if;

  return query
  select
    s.session_date,
    bool_or(s.visible) as visible,
    count(*) as slots_count,
    count(*) filter (where s.booked) as booked_count,
    coalesce(sum(r.pending_requests), 0)::bigint as pending_requests
  from public.amma_slots s
  left join lateral (
    select count(*) as pending_requests
      from public.amma_booking_requests br
     where br.slot_id = s.id
       and br.confirmed_at is null
       and br.expires_at >= now()
  ) r on true
  group by s.session_date
  order by s.session_date;
end;
$$;

create or replace function public.admin_create_amma_session(
  p_session_date date,
  p_visible boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_inserted integer;
begin
  if not public.is_amma_admin() then
    raise exception 'admin_access_required';
  end if;

  if p_session_date is null then
    raise exception 'missing_session_date';
  end if;

  if exists (
    select 1
      from public.amma_slots
     where session_date = p_session_date
  ) then
    raise exception 'session_already_exists';
  end if;

  insert into public.amma_slots (session_date, start_time, end_time, visible)
  values
    (p_session_date, '11:30', '12:00', coalesce(p_visible, false)),
    (p_session_date, '12:00', '12:30', coalesce(p_visible, false)),
    (p_session_date, '12:30', '13:00', coalesce(p_visible, false)),
    (p_session_date, '13:10', '13:40', coalesce(p_visible, false)),
    (p_session_date, '13:40', '14:10', coalesce(p_visible, false));

  get diagnostics v_inserted = row_count;

  return jsonb_build_object(
    'created', true,
    'session_date', p_session_date,
    'visible', coalesce(p_visible, false),
    'created_slots', v_inserted
  );
end;
$$;

create or replace function public.admin_update_amma_session(
  p_current_session_date date,
  p_new_session_date date,
  p_visible boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_updated integer;
begin
  if not public.is_amma_admin() then
    raise exception 'admin_access_required';
  end if;

  if p_current_session_date is null or p_new_session_date is null then
    raise exception 'missing_session_date';
  end if;

  if not exists (
    select 1
      from public.amma_slots
     where session_date = p_current_session_date
  ) then
    raise exception 'session_not_found';
  end if;

  if p_current_session_date <> p_new_session_date then
    if exists (
      select 1
        from public.amma_slots
       where session_date = p_new_session_date
    ) then
      raise exception 'target_session_already_exists';
    end if;

    if exists (
      select 1
        from public.amma_bookings b
        join public.amma_slots s
          on s.id = b.slot_id
       where s.session_date = p_current_session_date
    ) then
      raise exception 'session_has_bookings';
    end if;

    if exists (
      select 1
        from public.amma_booking_requests r
        join public.amma_slots s
          on s.id = r.slot_id
       where s.session_date = p_current_session_date
         and r.confirmed_at is null
         and r.expires_at >= now()
    ) then
      raise exception 'session_has_pending_requests';
    end if;
  end if;

  update public.amma_slots
     set session_date = p_new_session_date,
         visible = coalesce(p_visible, false)
   where session_date = p_current_session_date;

  get diagnostics v_updated = row_count;

  return jsonb_build_object(
    'updated', true,
    'updated_slots', v_updated,
    'current_session_date', p_current_session_date,
    'new_session_date', p_new_session_date,
    'visible', coalesce(p_visible, false)
  );
end;
$$;

drop function if exists public.admin_update_amma_session_date(date, date);

create or replace function public.admin_delete_amma_session(
  p_session_date date
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_deleted integer;
begin
  if not public.is_amma_admin() then
    raise exception 'admin_access_required';
  end if;

  if p_session_date is null then
    raise exception 'missing_session_date';
  end if;

  if not exists (
    select 1
      from public.amma_slots
     where session_date = p_session_date
  ) then
    raise exception 'session_not_found';
  end if;

  if exists (
    select 1
      from public.amma_bookings b
      join public.amma_slots s
        on s.id = b.slot_id
     where s.session_date = p_session_date
  ) then
    raise exception 'session_has_bookings';
  end if;

  if exists (
    select 1
      from public.amma_booking_requests r
      join public.amma_slots s
        on s.id = r.slot_id
     where s.session_date = p_session_date
       and r.confirmed_at is null
       and r.expires_at >= now()
  ) then
    raise exception 'session_has_pending_requests';
  end if;

  delete from public.amma_slots
   where session_date = p_session_date;

  get diagnostics v_deleted = row_count;

  return jsonb_build_object(
    'deleted', true,
    'session_date', p_session_date,
    'deleted_slots', v_deleted
  );
end;
$$;

revoke all on function public.book_amma_slot(bigint, text, text, text) from public;
revoke all on function public.create_amma_booking_request(bigint, text, text, text) from public;
revoke all on function public.confirm_amma_booking_request(uuid) from public;
revoke all on function public.cancel_amma_booking(uuid) from public;
revoke all on function public.is_amma_admin() from public;
revoke all on function public.admin_list_amma_reservations() from public;
revoke all on function public.admin_list_amma_sessions() from public;
revoke all on function public.admin_create_amma_session(date, boolean) from public;
revoke all on function public.admin_update_amma_session(date, date, boolean) from public;
revoke all on function public.admin_delete_amma_session(date) from public;

-- book_amma_slot est conservée pour compatibilité interne, mais n'est plus
-- exposée aux visiteurs. Les réservations publiques passent désormais par
-- create_amma_booking_request puis confirm_amma_booking_request.
grant execute on function public.create_amma_booking_request(bigint, text, text, text) to anon, authenticated;
grant execute on function public.confirm_amma_booking_request(uuid) to anon, authenticated;
grant execute on function public.cancel_amma_booking(uuid) to anon, authenticated;
grant execute on function public.is_amma_admin() to authenticated;
grant execute on function public.admin_list_amma_reservations() to authenticated;
grant execute on function public.admin_list_amma_sessions() to authenticated;
grant execute on function public.admin_create_amma_session(date, boolean) to authenticated;
grant execute on function public.admin_update_amma_session(date, date, boolean) to authenticated;
grant execute on function public.admin_delete_amma_session(date) to authenticated;

-- ==========================================================
-- Créneaux 2026 vus dans Evento
-- ==========================================================

insert into public.amma_slots (session_date, start_time, end_time)
values
  ('2026-09-15', '11:30', '12:00'),
  ('2026-09-15', '12:00', '12:30'),
  ('2026-09-15', '12:30', '13:00'),
  ('2026-09-15', '13:10', '13:40'),
  ('2026-09-15', '13:40', '14:10'),

  ('2026-10-15', '11:30', '12:00'),
  ('2026-10-15', '12:00', '12:30'),
  ('2026-10-15', '12:30', '13:00'),
  ('2026-10-15', '13:10', '13:40'),
  ('2026-10-15', '13:40', '14:10'),

  ('2026-11-12', '11:30', '12:00'),
  ('2026-11-12', '12:00', '12:30'),
  ('2026-11-12', '12:30', '13:00'),
  ('2026-11-12', '13:10', '13:40'),
  ('2026-11-12', '13:40', '14:10'),

  ('2026-12-08', '11:30', '12:00'),
  ('2026-12-08', '12:00', '12:30'),
  ('2026-12-08', '12:30', '13:00'),
  ('2026-12-08', '13:10', '13:40'),
  ('2026-12-08', '13:40', '14:10')
on conflict (session_date, start_time) do nothing;
