

-- NOTE :
-- Ce fichier configure uniquement le schéma PostgreSQL, les tables,
-- les fonctions RPC et les droits Supabase.
-- L'envoi des e-mails n'est pas géré ici : il est fait par l'Edge Function
-- supabase/functions/send-email/index.ts, avec les secrets SMTP Supabase.-- ==========================================================
-- Réservations AMMA — schéma Supabase
-- ==========================================================
-- À exécuter dans Supabase > SQL Editor.
--
-- Le navigateur peut :
--   - lire uniquement les créneaux (date, heure, Libre/Réservé)
--   - appeler deux fonctions sécurisées : réserver / annuler
--
-- Le navigateur NE PEUT PAS lire la table contenant les noms et e-mails.
-- ==========================================================

create extension if not exists pgcrypto;

create table if not exists public.amma_slots (
  id bigint generated by default as identity primary key,
  session_date date not null,
  start_time time not null,
  end_time time not null,
  booked boolean not null default false,
  created_at timestamptz not null default now(),

  constraint amma_slots_unique_slot unique (session_date, start_time),
  constraint amma_slots_valid_time check (end_time > start_time)
);

create table if not exists public.amma_bookings (
  id bigint generated by default as identity primary key,
  slot_id bigint not null unique references public.amma_slots(id) on delete cascade,
  firstname text not null,
  lastname text not null,
  email text not null,
  cancellation_token uuid not null unique default gen_random_uuid(),
  confirmation_email_sent_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.amma_bookings
  add column if not exists confirmation_email_sent_at timestamptz;

create table if not exists public.amma_booking_requests (
  id bigint generated by default as identity primary key,
  slot_id bigint not null references public.amma_slots(id) on delete cascade,
  firstname text not null,
  lastname text not null,
  email text not null,
  confirmation_token uuid not null unique default gen_random_uuid(),
  confirmation_email_sent_at timestamptz,
  confirmed_at timestamptz,
  expires_at timestamptz not null default now() + interval '2 hours',
  created_at timestamptz not null default now()
);

alter table public.amma_slots enable row level security;
alter table public.amma_bookings enable row level security;
alter table public.amma_booking_requests enable row level security;

-- Le public ne voit que l'état des créneaux.
drop policy if exists "Public can read AMMA slots" on public.amma_slots;
create policy "Public can read AMMA slots"
on public.amma_slots
for select
to anon
using (true);

-- AUCUNE policy SELECT/INSERT/UPDATE/DELETE sur amma_bookings ni
-- amma_booking_requests. Les tables contenant les noms/e-mails restent donc
-- inaccessibles directement depuis le navigateur.

create or replace function public.book_amma_slot(
  p_slot_id bigint,
  p_firstname text,
  p_lastname text,
  p_email text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_token uuid;
  v_updated integer;
begin
  if nullif(trim(p_firstname), '') is null
     or nullif(trim(p_lastname), '') is null
     or nullif(trim(p_email), '') is null then
    raise exception 'missing_fields';
  end if;

  if lower(trim(p_email)) !~ '^[^@\s]+@inria\.fr$' then
    raise exception 'invalid_email_domain';
  end if;

  update public.amma_slots
     set booked = true
   where id = p_slot_id
     and booked = false;

  get diagnostics v_updated = row_count;

  if v_updated <> 1 then
    raise exception 'slot_already_booked';
  end if;

  v_token := gen_random_uuid();

  insert into public.amma_bookings (
    slot_id,
    firstname,
    lastname,
    email,
    cancellation_token
  )
  values (
    p_slot_id,
    trim(p_firstname),
    trim(p_lastname),
    lower(trim(p_email)),
    v_token
  );

  return v_token;
end;
$$;

create or replace function public.create_amma_booking_request(
  p_slot_id bigint,
  p_firstname text,
  p_lastname text,
  p_email text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_token uuid;
begin
  if nullif(trim(p_firstname), '') is null
     or nullif(trim(p_lastname), '') is null
     or nullif(trim(p_email), '') is null then
    raise exception 'missing_fields';
  end if;

  if lower(trim(p_email)) !~ '^[^@\s]+@inria\.fr$' then
    raise exception 'invalid_email_domain';
  end if;

  if not exists (
    select 1
      from public.amma_slots
     where id = p_slot_id
       and booked = false
  ) then
    raise exception 'slot_already_booked';
  end if;

  v_token := gen_random_uuid();

  insert into public.amma_booking_requests (
    slot_id,
    firstname,
    lastname,
    email,
    confirmation_token
  )
  values (
    p_slot_id,
    trim(p_firstname),
    trim(p_lastname),
    lower(trim(p_email)),
    v_token
  );

  return v_token;
end;
$$;

create or replace function public.confirm_amma_booking_request(
  p_token uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.amma_booking_requests%rowtype;
  v_slot public.amma_slots%rowtype;
  v_cancellation_token uuid;
  v_updated integer;
begin
  select *
    into v_request
    from public.amma_booking_requests
   where confirmation_token = p_token
   for update;

  if v_request.id is null then
    raise exception 'request_not_found';
  end if;

  if v_request.confirmed_at is not null then
    raise exception 'request_already_confirmed';
  end if;

  if v_request.expires_at < now() then
    raise exception 'request_expired';
  end if;

  update public.amma_slots
     set booked = true
   where id = v_request.slot_id
     and booked = false
   returning * into v_slot;

  get diagnostics v_updated = row_count;

  if v_updated <> 1 then
    raise exception 'slot_already_booked';
  end if;

  v_cancellation_token := gen_random_uuid();

  insert into public.amma_bookings (
    slot_id,
    firstname,
    lastname,
    email,
    cancellation_token
  )
  values (
    v_request.slot_id,
    v_request.firstname,
    v_request.lastname,
    v_request.email,
    v_cancellation_token
  );

  update public.amma_booking_requests
     set confirmed_at = now()
   where id = v_request.id;

  return jsonb_build_object(
    'cancellation_token', v_cancellation_token,
    'session_date', v_slot.session_date,
    'start_time', v_slot.start_time,
    'end_time', v_slot.end_time
  );
end;
$$;

create or replace function public.cancel_amma_booking(
  p_token uuid
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_slot_id bigint;
begin
  delete from public.amma_bookings
   where cancellation_token = p_token
   returning slot_id into v_slot_id;

  if v_slot_id is null then
    return false;
  end if;

  update public.amma_slots
     set booked = false
   where id = v_slot_id;

  return true;
end;
$$;

revoke all on function public.book_amma_slot(bigint, text, text, text) from public;
revoke all on function public.create_amma_booking_request(bigint, text, text, text) from public;
revoke all on function public.confirm_amma_booking_request(uuid) from public;
revoke all on function public.cancel_amma_booking(uuid) from public;

grant execute on function public.book_amma_slot(bigint, text, text, text) to anon;
grant execute on function public.create_amma_booking_request(bigint, text, text, text) to anon;
grant execute on function public.confirm_amma_booking_request(uuid) to anon;
grant execute on function public.cancel_amma_booking(uuid) to anon;

-- ==========================================================
-- Créneaux 2026 vus dans Evento
-- ==========================================================

insert into public.amma_slots (session_date, start_time, end_time)
values
  ('2026-09-15', '11:30', '12:00'),
  ('2026-09-15', '12:00', '12:30'),
  ('2026-09-15', '12:30', '13:00'),
  ('2026-09-15', '13:10', '13:40'),
  ('2026-09-15', '13:40', '14:10'),

  ('2026-10-15', '11:30', '12:00'),
  ('2026-10-15', '12:00', '12:30'),
  ('2026-10-15', '12:30', '13:00'),
  ('2026-10-15', '13:10', '13:40'),
  ('2026-10-15', '13:40', '14:10'),

  ('2026-11-12', '11:30', '12:00'),
  ('2026-11-12', '12:00', '12:30'),
  ('2026-11-12', '12:30', '13:00'),
  ('2026-11-12', '13:10', '13:40'),
  ('2026-11-12', '13:40', '14:10'),

  ('2026-12-08', '11:30', '12:00'),
  ('2026-12-08', '12:00', '12:30'),
  ('2026-12-08', '12:30', '13:00'),
  ('2026-12-08', '13:10', '13:40'),
  ('2026-12-08', '13:40', '14:10')
on conflict (session_date, start_time) do nothing;
